### ISSUE TITLE
Youtube Videos are not displayed or played embedded

### ISSUE THREAD

**Issue by osm-frasch** [juliushaertl/integration_youtube#3]
Youtube videos are not displayed or played embedded
I have installed the app

NC 25.0.2
Talk-App:  Vers.: 15.0.3
App: YouTube integration: Vers. 0.1.1

PHP Version: 8.1.14
Speicherlimit: 528 MB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 4,9 GB

Erweiterungen: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, hash, fileinfo, filter, ftp, gd, gettext, gmp, json, iconv, SPL, intl, session, ldap, mbstring, standard, mysqlnd, exif, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, Reflection, imap, shmop, SimpleXML, snmp, soap, sockets, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zend_test, zip, apache2handler, apcu, imagick, redis, Zend OPcache

mysql-Version: 10.7.7 

Betriebssystem: Linux 5.4.0-29-generic x86_64
Prozessor: QEMU Virtual CPU version 2.5+ (4 cores)

**Comment by juliushaertl** [comment]
Where are you trying to see the embed? Also can you check your browser console for errors?

**Comment by osm-frasch** [comment]
I have posted a Youtube link in a TALK chat. 
It is only displayed as a thumbnail. If I am correct, a Youtube video should actually be loaded and playable within the chat.
Here is a screenshot excerpt

![Screenshot 2023-02-03 at 09-29-52 - Talk -HUB](https://user-images.githubusercontent.com/63851138/216551249-6ce9ba85-109e-4622-8049-118c4e63de97.png)

**Comment by juliushaertl** [comment]
Fixed with https://github.com/juliushaertl/integration_youtube/commit/e546868652deeef3a7a6f257aa74ca0fe4d958b4

I'll prepare a release somewhen next week, testing is still welcome if you want to manually apply the change. :)

**Comment by osm-frasch** [comment]
Thank you for the quick response. I will give feedback with the new Realease. I cannot test this manually...productive environment

**Comment by osm-frasch** [comment]
> Fixed with [e546868](https://github.com/juliushaertl/integration_youtube/commit/e546868652deeef3a7a6f257aa74ca0fe4d958b4)
> 
> I'll prepare a release somewhen next week, testing is still welcome if you want to manually apply the change. :)

Will you publish the release this week? I will give feedback quickly. I cannot do this manually. Thanks

**Comment by juliushaertl** [comment]
Just published as v0.1.2

**Comment by osm-frasch** [comment]
Thank you. I still have to wait a bit until it shows up in the NC backend appstore....

**Comment by osm-frasch** [comment]
I have just updated to the new version. However, I still get Youtube links in the chat only as previews. Exactly as described before
![Screenshot 2023-02-10 at 14-46-55- Talk-YoutubeLinkinTalkChat](https://user-images.githubusercontent.com/63851138/218108233-e2cfbd12-db6a-4f91-b562-25b7fb3111f3.png)

**Comment by osm-frasch** [comment]
Has the error been found? Does it only affect 25.0.2? 
I am still on NC 25.0.2 and will only switch to NC 25.0.4 after the weekend. How can I continue to help?

**Comment by juliushaertl** [comment]
Can you check again with 0.1.3 which I released earlier today?

**Comment by osm-frasch** [comment]
Great, thank you very much!. 
It works as it should. 
Tested under the above settings. (NC 25.0.2...). 
Have a nice weekend

**Comment by osm-frasch** [comment]
I have just installed the app (version 0.1.4) in the new NC 27.1.2. But there is no functionality, actually exactly as described earlier in this thread (under NC 25)

PhP 8.1.25, MySQL 8.0.32
